// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAGuadGpGxR2cUV4OPakm1muFJaRahGwl0',
    appId: '1:465222244060:web:c68dd3adc12fc125974619',
    messagingSenderId: '465222244060',
    projectId: 'cat-chat-9e872',
    authDomain: 'cat-chat-9e872.firebaseapp.com',
    storageBucket: 'cat-chat-9e872.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCFWVGbCQhHmRJBq3KzmUOn_ZQvwCZ1uDU',
    appId: '1:465222244060:android:414f5f59eb28ea7e974619',
    messagingSenderId: '465222244060',
    projectId: 'cat-chat-9e872',
    storageBucket: 'cat-chat-9e872.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCcC4Sph_ld_1hp54Cci9dLoAa_kdWw3e0',
    appId: '1:465222244060:ios:c677859b4873c0a6974619',
    messagingSenderId: '465222244060',
    projectId: 'cat-chat-9e872',
    storageBucket: 'cat-chat-9e872.appspot.com',
    iosClientId: '465222244060-ak78f2c3vtns288n9s9ak42dtdv8vt2d.apps.googleusercontent.com',
    iosBundleId: 'com.example.flashChat',
  );
}
